# Generated by Django 5.0.14 on 2026-05-18 23:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('raw_message', models.TextField()),
                ('source', models.CharField(default='whatsapp', max_length=32)),
                ('status', models.CharField(default='received', max_length=32)),
                ('routing_location_id', models.CharField(blank=True, max_length=64, null=True)),
                ('routing_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id', '-created_at'], name='candidate_client__16ca34_idx')],
            },
        ),
    ]
