# Generated by Django 5.0.14 on 2026-05-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('routing_strategy', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('max_capacity', models.IntegerField()),
                ('current_load', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='configapp.client')),
            ],
            options={
                'db_table': 'location',
                'ordering': ['client', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='LocationOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('is_open', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='configapp.location')),
            ],
            options={
                'db_table': 'location_opening',
                'unique_together': {('location', 'role')},
            },
        ),
    ]
