# Generated by Django 5.0.14 on 2026-05-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_event',
            },
        ),
        migrations.CreateModel(
            name='RoutingDecision',
            fields=[
                ('candidate_id', models.UUIDField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('extracted_role', models.CharField(blank=True, max_length=64, null=True)),
                ('extracted_city', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
                ('selected_location_id', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'routing_decision',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['client_id', '-decided_at'], name='routing_dec_client__044644_idx')],
            },
        ),
    ]
